---
name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test (Node.js v${{ matrix.node }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - '20'
          - '22'
        include:
          - os: ubuntu-latest
            os_name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
          node_auth_token: ${{ secrets.GH_TOKEN }}
      - name: Test
        run: npm test
  lint:
    name: Lint (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - '20'
          - '22'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
          node_auth_token: ${{ secrets.GH_TOKEN }}
      - name: Lint
        run: npm run lint
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets:
      node_auth_token: ${{ secrets.GH_TOKEN }}
  install:
    name: Install (Node.js v${{ matrix.node }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - '20'
          - '22'
        include:
          - os: ubuntu-latest
            os_name: Linux
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: .
      - name: Find packages
        uses: tj-actions/glob@v21
        id: packages
        with:
          files: '*.tgz'
      - name: Create package.json
        uses: DamianReeves/write-file-action@v1.3
        with:
          write-mode: overwrite
          path: package.json
          contents: |
            {"type":"module"}
      - name: Create index.js
        uses: DamianReeves/write-file-action@v1.3
        with:
          write-mode: overwrite
          path: index.js
          contents: |
            import '@seamapi/makenew-tsmodule'
      - name: Install
        run: npm install --ignore-scripts --save ${{ steps.packages.outputs.paths }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Rebuild Node.js modules
        shell: bash
        run: npm rebuild
      - name: Run postinstall script
        shell: bash
        run: npm run postinstall --if-present
      - name: Run prepare script
        shell: bash
        run: npm run prepare --if-present
      - name: Run
        run: node index.js
  typecheck:
    name: Typecheck (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - '20'
          - '22'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
          node_auth_token: ${{ secrets.GH_TOKEN }}
      - name: Typecheck
        run: npm run typecheck
